### ISSUE TITLE
Python implementation

### ISSUE THREAD

**Issue by FlorisCalkoen** [domoritz/line-heatmap#5]
Would be nice to have this function implemented in Python as well! Or do you know whether something similar exists in Python?

**Comment by domoritz** [comment]
There are. I asked another researcher who wrote a nice Python version to see whether they can share it. 

I also wrote a simple Python version I wrote some time ago. It creates a heatmap of stock data.

```py
width = 300
height = 200

# compute y extent and x extent

y_extent = [0, df.Close.max()]
yscale = np.vectorize(lambda v: (v - y_extent[0]) / (y_extent[1] - y_extent[0]) * (height - 1))

x_extent = [df.Timestamp.min(), df.Timestamp.max()]

# discretize x and apply y scale
xbins = np.linspace(x_extent[0], x_extent[1], num=width)
df['X'] = np.digitize(df.Timestamp, xbins)

df['Y'] = yscale(df.Close)

groups = df.groupby(['Symbol'])

# compute heatmap
data = np.zeros((height, width), dtype=np.float32)

img  = Image.new('I', (width, height), color=0)
draw = ImageDraw.Draw(img)

for name, series in groups:
    prev_x = None
    prev_y = None

    for idx, record in series.iterrows():
        if prev_x is not None and prev_y is not None:
            draw.line([prev_x, prev_y, record.X, record.Y])
        
        prev_x = record.X
        prev_y = record.Y

    series_data = np.array(img)
    
    # normalize by column
    series_data = series_data / series_data.sum(axis=0)[:None]
    
    # add to data
    data += np.nan_to_num(series_data)
    
    draw.rectangle([(0,0), (width,height)], fill=0)
```

![stocks_heat](https://user-images.githubusercontent.com/589034/99431504-ba09c880-28bf-11eb-9361-776a94b63887.png)

**Comment by mleznik** [comment]
Hi @FlorisCalkoen, 

I have uploaded our code to: https://github.com/omi-uulm/denseline
Hope this helps!

Thank you again @domoritz for pinging me :-)

**Comment by FlorisCalkoen** [comment]
Thanks! Meanwhile I made a workaround with Datashader, but this looks great as well. Closing this issue now.

**Comment by domoritz** [comment]
Nice. Would you share the code? Does it do the normalization?

**Comment by FlorisCalkoen** [comment]
Sure! You can find a small example here: https://github.com/FlorisCalkoen/notebooks/blob/master/line_density.ipynb

**Comment by domoritz** [comment]
Thanks for sharing! I don't see the normalization by column in your code. Am I missing something?

**Comment by FlorisCalkoen** [comment]
Hi there, I'm afraid it doesn't do the normalization indeed. Initially I was just looking for a quick density plot of many time series - not paying attention to the normalization. When I have some time, I'll check if Datashader is still beneficial when normalization is included.

**Comment by domoritz** [comment]
I see. Without the normalization, the generated densities can be very misleading so I'd recommend that you look into normalization. I think datashader could still be useful for drawing each line.

**Comment by mleznik** [comment]
hi @FlorisCalkoen, since @domoritz and myself already had that discussion and i have the receipts to show what he means, attached two images with and without normalization, do note that is presents a skewed representation. 

![bb_data_normalized_500_500](https://user-images.githubusercontent.com/1878575/100610279-b3dc0900-330f-11eb-8e3e-7030e29507de.png)
![bb_data_500_500](https://user-images.githubusercontent.com/1878575/100610282-b4749f80-330f-11eb-96db-d8e931d7533f.png)
